name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: termux
      run: sudo git clone https://github.com/termux/termux-packages --depth=1 && cd termux-packages && sudo bash ./scripts/setup-ubuntu.sh && bash ./scripts/setup-android-sdk.sh && sudo bash ./scripts/properties.sh && sudo ./build-package.sh bash
