name: termux-packages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: cloning repository
      run: sudo apt upgrade -y && git clone https://github.com/funnymdzz/termux-hrhr $HOME/termux-packages
    - name: installing ndk
      run: cd $HOME/termux-packages && sudo bash ./scripts/setup-ubuntu.sh && sudo bash ./scripts/setup-android-sdk.sh
    - name: building 
      run: mkdir -p /home/runner/work/termux-hrhr/termux-hrhr/debs && cd $HOME/termux-packages && sudo bash ./build-package.sh python && cp -r $HOME/termux-packages/debs/* /home/runner/work/termux-hrhr/termux-hrhr/debs
    - name : Upload packages
      uses: actions/upload-artifact@master
      with:
        name: debs
        path: debs
