name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: termux/package-builder

    steps:
    - name: termux
      run: apt install git -y && git clone https://github.com/termux/termux-packages /home/builder/termux-packages --depth=1 && bash /home/builder/termux-packages/build-package.sh bash
