name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker://termux/package-builder
    - name: termux
      run: echo Hello, world!
    - name: Run a multi-line script
      run: cd /home/builder && ls && ./build-package.sh bash
