name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: termux/package-builder

    steps:
    - name: termux
      run: sudo git clone https://github.com/termux/termux-packages /home/builder/termux-packages --depth=1 && cd /home/builder/termux-packages.sh && sudo bash build-package.sh bash
